---
- name: "Install ca-certificates"
  package:
    pkg: "{{ install_ca_certificates_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "ca-certificates"
