---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing ca-certificates on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_ca_certificates_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "ca_certificates is defined"
  tags:
    - "ca-certificates"
- name: "Install ca-certificates"
  package:
    pkg: "{{ install_ca_certificates_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "ca_certificates is defined"
  tags:
    - "ca-certificates"
